import React from "react";
import ReactDOM from "react-dom/client";
import { Amplify } from "aws-amplify";
import { App } from "./App";
import outputs from "../amplify_outputs.json";
import "./index.css";

// `amplify_outputs.json` is generated by `npx ampx sandbox` (local) or by the
// backend deploy step in CI (see amplify.yml). It is gitignored; a placeholder
// ships in the repo so the app builds before the first deploy.
Amplify.configure(outputs);

ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
);
